// <auto-generated />
using System;
using CommandProjectUniversal.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CommandProjectUniversal.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.22");

            modelBuilder.Entity("CommandProjectUniversal.Models.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "RU",
                            Name = "Россия"
                        },
                        new
                        {
                            Id = 2,
                            Code = "UA",
                            Name = "Украина"
                        },
                        new
                        {
                            Id = 3,
                            Code = "BY",
                            Name = "Беларусь"
                        });
                });

            modelBuilder.Entity("CommandProjectUniversal.Models.Customer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Customers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "Delfina.Lindgren8@hotmail.com",
                            Name = "Noelia Monahan",
                            Phone = "888.872.5597"
                        },
                        new
                        {
                            Id = 2,
                            Email = "Piper99@gmail.com",
                            Name = "Guillermo Ortiz",
                            Phone = "1-568-214-0760"
                        },
                        new
                        {
                            Id = 3,
                            Email = "Mia54@yahoo.com",
                            Name = "Dorian Rath",
                            Phone = "841-421-2861"
                        },
                        new
                        {
                            Id = 4,
                            Email = "Bryce.Douglas@yahoo.com",
                            Name = "Carmelo Heidenreich",
                            Phone = "1-666-404-9404 x09892"
                        },
                        new
                        {
                            Id = 5,
                            Email = "Jayce_Kshlerin@yahoo.com",
                            Name = "Sandra Lindgren",
                            Phone = "581-379-7176 x19954"
                        },
                        new
                        {
                            Id = 6,
                            Email = "Green38@gmail.com",
                            Name = "Pat Terry",
                            Phone = "(738) 256-5325 x43826"
                        },
                        new
                        {
                            Id = 7,
                            Email = "Nona.Doyle16@yahoo.com",
                            Name = "Sonia Balistreri",
                            Phone = "(556) 769-4182"
                        },
                        new
                        {
                            Id = 8,
                            Email = "Dessie29@yahoo.com",
                            Name = "Verla Nolan",
                            Phone = "366.428.6509"
                        },
                        new
                        {
                            Id = 9,
                            Email = "Olaf.Dicki61@yahoo.com",
                            Name = "Destin Kerluke",
                            Phone = "1-956-989-0138 x152"
                        },
                        new
                        {
                            Id = 10,
                            Email = "Claud.Bradtke@yahoo.com",
                            Name = "Lauryn Cormier",
                            Phone = "1-408-932-8719 x49535"
                        });
                });

            modelBuilder.Entity("CommandProjectUniversal.Models.Provider", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<int>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Providers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "ул. Гончарная, д. 30, Москва, 115172",
                            CountryId = 1,
                            Email = "info@rt.ru",
                            Name = "Ростелеком",
                            Phone = "+7 (495) 771-11-11"
                        },
                        new
                        {
                            Id = 2,
                            Address = "ул. Марксистская, д. 4, Москва, 109147",
                            CountryId = 1,
                            Email = "info@mts.ru",
                            Name = "МТС",
                            Phone = "+7 (495) 788-00-00"
                        },
                        new
                        {
                            Id = 3,
                            Address = "ул. 2-я Хуторская, д. 38А, стр. 26, Москва, 127287",
                            CountryId = 1,
                            Email = "info@beeline.ru",
                            Name = "Билайн",
                            Phone = "+7 (495) 797-27-27"
                        });
                });

            modelBuilder.Entity("CommandProjectUniversal.Models.Sale", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CustomerId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SaleDate")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("SalePrice")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServiceId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.HasIndex("ServiceId")
                        .IsUnique();

                    b.ToTable("Sales");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CustomerId = 7,
                            Description = "Et omnis est suscipit aut.",
                            SaleDate = new DateTime(2024, 8, 25, 16, 5, 23, 597, DateTimeKind.Local).AddTicks(8466),
                            SalePrice = 1866.103417644505800m,
                            ServiceId = 1
                        },
                        new
                        {
                            Id = 2,
                            CustomerId = 2,
                            Description = "Laboriosam facilis est dolor qui.",
                            SaleDate = new DateTime(2025, 4, 18, 2, 17, 3, 39, DateTimeKind.Local).AddTicks(5100),
                            SalePrice = 2054.94295971066400m,
                            ServiceId = 2
                        },
                        new
                        {
                            Id = 3,
                            CustomerId = 5,
                            Description = "Ut optio dolorum repudiandae sequi nihil commodi.",
                            SaleDate = new DateTime(2025, 4, 4, 1, 8, 24, 140, DateTimeKind.Local).AddTicks(7845),
                            SalePrice = 3231.595655948372200m,
                            ServiceId = 3
                        },
                        new
                        {
                            Id = 4,
                            CustomerId = 6,
                            Description = "Quo earum eos odio occaecati cupiditate sit nihil.",
                            SaleDate = new DateTime(2024, 3, 18, 6, 43, 49, 824, DateTimeKind.Local).AddTicks(1016),
                            SalePrice = 3624.166352970587800m,
                            ServiceId = 4
                        },
                        new
                        {
                            Id = 5,
                            CustomerId = 9,
                            Description = "Odio quia dolorem accusantium sit.",
                            SaleDate = new DateTime(2024, 3, 22, 4, 54, 17, 167, DateTimeKind.Local).AddTicks(1658),
                            SalePrice = 1150.566391279122200m,
                            ServiceId = 5
                        });
                });

            modelBuilder.Entity("CommandProjectUniversal.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContractNumber")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("InstallationDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServicePlanId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ServicePlanId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "929 Skiles Forks, Kemmerborough, Venezuela",
                            ContractNumber = "adenokebh3",
                            InstallationDate = new DateTime(2022, 6, 3, 4, 37, 36, 248, DateTimeKind.Local).AddTicks(1779),
                            IsActive = false,
                            Name = "",
                            ServicePlanId = 9
                        },
                        new
                        {
                            Id = 2,
                            Address = "0933 Schowalter Fields, Port Ulices, China",
                            ContractNumber = "suikkxlmnk",
                            InstallationDate = new DateTime(2025, 1, 5, 2, 12, 30, 386, DateTimeKind.Local).AddTicks(9451),
                            IsActive = false,
                            Name = "",
                            ServicePlanId = 3
                        },
                        new
                        {
                            Id = 3,
                            Address = "176 Deckow Way, West Carolyneview, China",
                            ContractNumber = "wl7kkohzmk",
                            InstallationDate = new DateTime(2021, 9, 20, 22, 49, 19, 509, DateTimeKind.Local).AddTicks(6480),
                            IsActive = false,
                            Name = "",
                            ServicePlanId = 7
                        },
                        new
                        {
                            Id = 4,
                            Address = "28987 Schuppe Avenue, Bernhardchester, Northern Mariana Islands",
                            ContractNumber = "2a7e0ugkdp",
                            InstallationDate = new DateTime(2022, 3, 17, 5, 17, 26, 50, DateTimeKind.Local).AddTicks(8348),
                            IsActive = false,
                            Name = "",
                            ServicePlanId = 8
                        },
                        new
                        {
                            Id = 5,
                            Address = "5150 Hoeger Pines, Charleymouth, Ukraine",
                            ContractNumber = "ndavtc2a6o",
                            InstallationDate = new DateTime(2022, 2, 21, 11, 44, 20, 653, DateTimeKind.Local).AddTicks(3352),
                            IsActive = false,
                            Name = "",
                            ServicePlanId = 6
                        },
                        new
                        {
                            Id = 6,
                            Address = "69075 Miller Mountains, Prudenceland, Netherlands Antilles",
                            ContractNumber = "tibbrvi3ts",
                            InstallationDate = new DateTime(2022, 6, 18, 18, 37, 20, 561, DateTimeKind.Local).AddTicks(269),
                            IsActive = true,
                            Name = "",
                            ServicePlanId = 8
                        },
                        new
                        {
                            Id = 7,
                            Address = "04113 Alejandra Mountains, Krajcikhaven, Honduras",
                            ContractNumber = "b98kogxjhl",
                            InstallationDate = new DateTime(2025, 1, 1, 16, 7, 8, 818, DateTimeKind.Local).AddTicks(2213),
                            IsActive = true,
                            Name = "",
                            ServicePlanId = 6
                        },
                        new
                        {
                            Id = 8,
                            Address = "416 Thelma Trafficway, West Lincoln, Comoros",
                            ContractNumber = "vdml3fdyy9",
                            InstallationDate = new DateTime(2022, 7, 1, 11, 35, 39, 432, DateTimeKind.Local).AddTicks(7768),
                            IsActive = true,
                            Name = "",
                            ServicePlanId = 5
                        },
                        new
                        {
                            Id = 9,
                            Address = "04851 Champlin Rest, New Murlmouth, Syrian Arab Republic",
                            ContractNumber = "0a30fxoalc",
                            InstallationDate = new DateTime(2024, 11, 6, 19, 34, 44, 907, DateTimeKind.Local).AddTicks(2667),
                            IsActive = false,
                            Name = "",
                            ServicePlanId = 7
                        },
                        new
                        {
                            Id = 10,
                            Address = "910 Vada Alley, West Neldaland, Egypt",
                            ContractNumber = "f236nfhfnj",
                            InstallationDate = new DateTime(2023, 4, 21, 4, 0, 34, 717, DateTimeKind.Local).AddTicks(7800),
                            IsActive = false,
                            Name = "",
                            ServicePlanId = 3
                        },
                        new
                        {
                            Id = 11,
                            Address = "432 Howell Motorway, Binsmouth, French Guiana",
                            ContractNumber = "bi804op5qf",
                            InstallationDate = new DateTime(2024, 11, 7, 12, 21, 44, 956, DateTimeKind.Local).AddTicks(5057),
                            IsActive = false,
                            Name = "",
                            ServicePlanId = 2
                        },
                        new
                        {
                            Id = 12,
                            Address = "256 Stiedemann Court, Justineland, Cote d'Ivoire",
                            ContractNumber = "g6gx418v12",
                            InstallationDate = new DateTime(2022, 4, 3, 10, 41, 47, 777, DateTimeKind.Local).AddTicks(8656),
                            IsActive = false,
                            Name = "",
                            ServicePlanId = 5
                        },
                        new
                        {
                            Id = 13,
                            Address = "8564 Guy Falls, Port Clara, Nauru",
                            ContractNumber = "kvq49sda5q",
                            InstallationDate = new DateTime(2022, 7, 20, 7, 38, 9, 948, DateTimeKind.Local).AddTicks(5622),
                            IsActive = false,
                            Name = "",
                            ServicePlanId = 8
                        },
                        new
                        {
                            Id = 14,
                            Address = "1008 Emmitt Brooks, Freidatown, Falkland Islands (Malvinas)",
                            ContractNumber = "mgly9vm1a6",
                            InstallationDate = new DateTime(2023, 1, 9, 21, 47, 3, 749, DateTimeKind.Local).AddTicks(6913),
                            IsActive = true,
                            Name = "",
                            ServicePlanId = 9
                        },
                        new
                        {
                            Id = 15,
                            Address = "6973 Zackary Circles, Port Cliffordchester, Ecuador",
                            ContractNumber = "ql090xcw48",
                            InstallationDate = new DateTime(2023, 5, 21, 16, 6, 58, 681, DateTimeKind.Local).AddTicks(3140),
                            IsActive = false,
                            Name = "",
                            ServicePlanId = 2
                        });
                });

            modelBuilder.Entity("CommandProjectUniversal.Models.ServicePlan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CountryId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DataLimitGB")
                        .HasColumnType("INTEGER");

                    b.Property<int>("LaunchYear")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("PricePerMonth")
                        .HasColumnType("TEXT");

                    b.Property<int>("ProviderId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SpeedMbps")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.HasIndex("ProviderId");

                    b.ToTable("ServicePlans");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 1,
                            DataLimitGB = 0,
                            LaunchYear = 2020,
                            Name = "Онлайн 100",
                            PricePerMonth = 550m,
                            ProviderId = 1,
                            SpeedMbps = 100
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 1,
                            DataLimitGB = 0,
                            LaunchYear = 2019,
                            Name = "Онлайн 200",
                            PricePerMonth = 750m,
                            ProviderId = 1,
                            SpeedMbps = 200
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 1,
                            DataLimitGB = 0,
                            LaunchYear = 2021,
                            Name = "Онлайн 500",
                            PricePerMonth = 1200m,
                            ProviderId = 1,
                            SpeedMbps = 500
                        },
                        new
                        {
                            Id = 4,
                            CountryId = 1,
                            DataLimitGB = 0,
                            LaunchYear = 2018,
                            Name = "Интернет 100",
                            PricePerMonth = 500m,
                            ProviderId = 2,
                            SpeedMbps = 100
                        },
                        new
                        {
                            Id = 5,
                            CountryId = 1,
                            DataLimitGB = 0,
                            LaunchYear = 2020,
                            Name = "Интернет 300",
                            PricePerMonth = 700m,
                            ProviderId = 2,
                            SpeedMbps = 300
                        },
                        new
                        {
                            Id = 6,
                            CountryId = 1,
                            DataLimitGB = 0,
                            LaunchYear = 2022,
                            Name = "Интернет 500",
                            PricePerMonth = 1000m,
                            ProviderId = 2,
                            SpeedMbps = 500
                        },
                        new
                        {
                            Id = 7,
                            CountryId = 1,
                            DataLimitGB = 0,
                            LaunchYear = 2017,
                            Name = "Интернет 50",
                            PricePerMonth = 400m,
                            ProviderId = 3,
                            SpeedMbps = 50
                        },
                        new
                        {
                            Id = 8,
                            CountryId = 1,
                            DataLimitGB = 0,
                            LaunchYear = 2019,
                            Name = "Интернет 100",
                            PricePerMonth = 600m,
                            ProviderId = 3,
                            SpeedMbps = 100
                        },
                        new
                        {
                            Id = 9,
                            CountryId = 1,
                            DataLimitGB = 0,
                            LaunchYear = 2021,
                            Name = "Интернет 300",
                            PricePerMonth = 850m,
                            ProviderId = 3,
                            SpeedMbps = 300
                        });
                });

            modelBuilder.Entity("CommandProjectUniversal.Models.Provider", b =>
                {
                    b.HasOne("CommandProjectUniversal.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");
                });

            modelBuilder.Entity("CommandProjectUniversal.Models.Sale", b =>
                {
                    b.HasOne("CommandProjectUniversal.Models.Customer", "Customer")
                        .WithMany()
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CommandProjectUniversal.Models.Service", "Service")
                        .WithOne("Sale")
                        .HasForeignKey("CommandProjectUniversal.Models.Sale", "ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Customer");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("CommandProjectUniversal.Models.Service", b =>
                {
                    b.HasOne("CommandProjectUniversal.Models.ServicePlan", "ServicePlan")
                        .WithMany()
                        .HasForeignKey("ServicePlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServicePlan");
                });

            modelBuilder.Entity("CommandProjectUniversal.Models.ServicePlan", b =>
                {
                    b.HasOne("CommandProjectUniversal.Models.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CommandProjectUniversal.Models.Provider", "Provider")
                        .WithMany()
                        .HasForeignKey("ProviderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Country");

                    b.Navigation("Provider");
                });

            modelBuilder.Entity("CommandProjectUniversal.Models.Service", b =>
                {
                    b.Navigation("Sale");
                });
#pragma warning restore 612, 618
        }
    }
}
